### PR TITLE
Add the new certificate

### PR DESCRIPTION
**Pull request by fables-tales**
I had a call with Myron today and we both have the private key and the passphrase
for creating signatures with the certificate.

The new certificate is a 4096 bit RSA key with a 10 year expiry.

In order to distribute the certificate effectively within the network of trust, we've
decided to add signatures for each of the core team members that assert the
certificate is valid. 

@rspec/rspec  If you don't yet have a keypair and would like to generate one
I'll happily walk you through the process. If you do have a keypair you can
generate the signature with `gpg --armor --detach-sig certs/rspec.pem` but
you should not do so until you are sure that both my key and the certificate are valid.

If my key is already in your network of trust via people that have signed it, you can
verify the signature with: `gpg --verify certs/samphippen.asc certs/rspec.pem`. 
Otherwise, let's set up a call to do a key exchange and we can verify the
certificate that way.

### CODE REVIEW

**Comment by JonRowe** [comment]
For me this will have to wait until at least the 3rd of Jan but I'm onboard otherwise :)

**Comment by myronmarston** [comment]
What's left to do for this?  Is there any benefit to keeping the old cert around?

**Comment by myronmarston** [comment]
BTW Sam, I forgot what the pass phrase was and also how to extract it from the encrypted file you gave me...so we'll have to touch base again.

**Comment by myronmarston** [comment]
Merged.  I figured out how to build gems with this.

**Pull request merged**
