### PR TITLE
Activating Open Collective

### PR DESCRIPTION
**Pull request by monkeywithacupcake**
Hi, I'm making updates for Open Collective. Either you or a supporter signed this repo up for Open Collective. This pull request adds backers and sponsors from your Open Collective https://opencollective.com/rspec ❤️
  
  It adds two badges at the top to show the latest number of backers and sponsors. It also adds placeholders so that the avatar/logo of new backers/sponsors can automatically be shown without having to update your README.md. [[more info](https://github.com/opencollective/opencollective/wiki/Github-banner)]. See how it looks on [this repo](https://github.com/apex/apex#backers).
You can also add a "Donate" button to your website and automatically show your backers and sponsors there with our widgets. Have a look here: https://opencollective.com/widgets

  P.S: As with any pull request, feel free to comment or suggest changes. The only thing "required" are the placeholders on the README because we believe it's important to acknowledge the people in your community that are contributing (financially or with code!).

  Thank you for your great contribution to the open source community. You are awesome! 🙌
  And welcome to the open collective community! 😊

  Come chat with us in the #opensource channel on https://slack.opencollective.com - great place to ask questions and share best practices with other open source sustainers!

### CODE REVIEW

**Comment by JonRowe** [comment]
Can we just add the badges? You can already find our contributors via Github, and we shout out to them in blog posts every time we do a release.

**Comment by myronmarston** [comment]
More generally, the list of contributors is only the list of contributors to _this_ repository.  This is the RSpec meta-gem that doesn't really have any code.  All the substantial contributions are on the other repos (rspec/rspec-core, rspec/rspec-expectations, rspec/rspec-mocks, rspec/rspec-support, rspec/rspec-rails).  I'd rather not include a list of contributors that leaves so many people out.  If there's a way to generate a list based on the contributors to those repositories I'd be more included to include it!

**Comment by monkeywithacupcake** [comment]
Yes, you can use just the badges - perhaps make a separate link somewhere for people to become backers and sponsors. 
I think that you can probably roll your own contributors image from all of the github contributor graphs, but it won't pull in through open collective as far as I know.

**Comment by pirj** [comment]
I guess this is pretty much done with Github's Sponsor button that includes a link to our page on OpenCollective. Additional badges and the list of donations seems redundant, as this information is available on a dedicated page. Updating this list as donations come in is a burden that we don't really want to carry.

We're really grateful to work with OpenCollective. Please let us know if there's some guideline on how the projects sponsored through OpenCollective should and typically place links/badges/other information.

image

**Pull request closed without merging**
